# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.institutions_api import InstitutionsApi


class TestInstitutionsApi(unittest.TestCase):
    """ InstitutionsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.institutions_api.InstitutionsApi()

    def tearDown(self):
        pass

    def test_account_institution_curation(self):
        """
        Test case for account_institution_curation

        Institution Curation Review
        """
        pass

    def test_account_institution_curation_comments(self):
        """
        Test case for account_institution_curation_comments

        Institution Curation Review Comments
        """
        pass

    def test_account_institution_curation_comments_0(self):
        """
        Test case for account_institution_curation_comments_0

        POST Institution Curation Review Comment
        """
        pass

    def test_account_institution_curations(self):
        """
        Test case for account_institution_curations

        Institution Curation Reviews
        """
        pass

    def test_custom_fields_list(self):
        """
        Test case for custom_fields_list

        Private account institution group custom fields
        """
        pass

    def test_custom_fields_upload(self):
        """
        Test case for custom_fields_upload

        Custom fields values files upload
        """
        pass

    def test_institution_articles(self):
        """
        Test case for institution_articles

        Public Licenses
        """
        pass

    def test_institution_hrfeed_upload(self):
        """
        Test case for institution_hrfeed_upload

        Private Institution HRfeed Upload
        """
        pass

    def test_private_account_institution_user(self):
        """
        Test case for private_account_institution_user

        Private Account Institution User
        """
        pass

    def test_private_categories_list(self):
        """
        Test case for private_categories_list

        Private Account Categories
        """
        pass

    def test_private_group_embargo_options_details(self):
        """
        Test case for private_group_embargo_options_details

        Private Account Institution Group Embargo Options
        """
        pass

    def test_private_institution_account_group_role_delete(self):
        """
        Test case for private_institution_account_group_role_delete

        Delete Institution Account Group Role
        """
        pass

    def test_private_institution_account_group_roles(self):
        """
        Test case for private_institution_account_group_roles

        List Institution Account Group Roles
        """
        pass

    def test_private_institution_account_group_roles_create(self):
        """
        Test case for private_institution_account_group_roles_create

        Add Institution Account Group Roles
        """
        pass

    def test_private_institution_accounts_create(self):
        """
        Test case for private_institution_accounts_create

        Create new Institution Account
        """
        pass

    def test_private_institution_accounts_list(self):
        """
        Test case for private_institution_accounts_list

        Private Account Institution Accounts
        """
        pass

    def test_private_institution_accounts_search(self):
        """
        Test case for private_institution_accounts_search

        Private Account Institution Accounts Search
        """
        pass

    def test_private_institution_accounts_update(self):
        """
        Test case for private_institution_accounts_update

        Update Institution Account
        """
        pass

    def test_private_institution_articles(self):
        """
        Test case for private_institution_articles

        Private Institution Articles
        """
        pass

    def test_private_institution_details(self):
        """
        Test case for private_institution_details

        Private Account Institutions
        """
        pass

    def test_private_institution_embargo_options_details(self):
        """
        Test case for private_institution_embargo_options_details

        Private Account Institution embargo options
        """
        pass

    def test_private_institution_groups_list(self):
        """
        Test case for private_institution_groups_list

        Private Account Institution Groups
        """
        pass

    def test_private_institution_roles_list(self):
        """
        Test case for private_institution_roles_list

        Private Account Institution Roles
        """
        pass


if __name__ == '__main__':
    unittest.main()
