# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.curation import Curation


class TestCuration(unittest.TestCase):
    """ Curation unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCuration(self):
        """
        Test Curation
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.curation.Curation()
        pass


if __name__ == '__main__':
    unittest.main()
