# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.other_api import OtherApi


class TestOtherApi(unittest.TestCase):
    """ OtherApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.other_api.OtherApi()

    def tearDown(self):
        pass

    def test_categories_list(self):
        """
        Test case for categories_list

        Public Categories
        """
        pass

    def test_file_download(self):
        """
        Test case for file_download

        Public File Download
        """
        pass

    def test_item_types_list(self):
        """
        Test case for item_types_list

        Item Types
        """
        pass

    def test_licenses_list(self):
        """
        Test case for licenses_list

        Public Licenses
        """
        pass

    def test_private_account(self):
        """
        Test case for private_account

        Private Account information
        """
        pass

    def test_private_funding_search(self):
        """
        Test case for private_funding_search

        Search Funding
        """
        pass

    def test_private_licenses_list(self):
        """
        Test case for private_licenses_list

        Private Account Licenses
        """
        pass


if __name__ == '__main__':
    unittest.main()
