# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.projects_api import ProjectsApi


class TestProjectsApi(unittest.TestCase):
    """ ProjectsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.projects_api.ProjectsApi()

    def tearDown(self):
        pass

    def test_private_project_article_delete(self):
        """
        Test case for private_project_article_delete

        Delete project article
        """
        pass

    def test_private_project_article_details(self):
        """
        Test case for private_project_article_details

        Project article details
        """
        pass

    def test_private_project_article_file(self):
        """
        Test case for private_project_article_file

        Project article file details
        """
        pass

    def test_private_project_article_files(self):
        """
        Test case for private_project_article_files

        Project article list files
        """
        pass

    def test_private_project_articles_create(self):
        """
        Test case for private_project_articles_create

        Create project article
        """
        pass

    def test_private_project_articles_list(self):
        """
        Test case for private_project_articles_list

        List project articles
        """
        pass

    def test_private_project_collaborator_delete(self):
        """
        Test case for private_project_collaborator_delete

        Remove project collaborator
        """
        pass

    def test_private_project_collaborators_invite(self):
        """
        Test case for private_project_collaborators_invite

        Invite project collaborators
        """
        pass

    def test_private_project_collaborators_list(self):
        """
        Test case for private_project_collaborators_list

        List project collaborators
        """
        pass

    def test_private_project_create(self):
        """
        Test case for private_project_create

        Create project
        """
        pass

    def test_private_project_delete(self):
        """
        Test case for private_project_delete

        Delete project
        """
        pass

    def test_private_project_details(self):
        """
        Test case for private_project_details

        View project details
        """
        pass

    def test_private_project_leave(self):
        """
        Test case for private_project_leave

        Private Project Leave
        """
        pass

    def test_private_project_note(self):
        """
        Test case for private_project_note

        Project note details
        """
        pass

    def test_private_project_note_delete(self):
        """
        Test case for private_project_note_delete

        Delete project note
        """
        pass

    def test_private_project_note_update(self):
        """
        Test case for private_project_note_update

        Update project note
        """
        pass

    def test_private_project_notes_create(self):
        """
        Test case for private_project_notes_create

        Create project note
        """
        pass

    def test_private_project_notes_list(self):
        """
        Test case for private_project_notes_list

        List project notes
        """
        pass

    def test_private_project_publish(self):
        """
        Test case for private_project_publish

        Private Project Publish
        """
        pass

    def test_private_project_update(self):
        """
        Test case for private_project_update

        Update project
        """
        pass

    def test_private_projects_list(self):
        """
        Test case for private_projects_list

        Private Projects
        """
        pass

    def test_private_projects_search(self):
        """
        Test case for private_projects_search

        Private Projects search
        """
        pass

    def test_project_articles(self):
        """
        Test case for project_articles

        Public Project Articles
        """
        pass

    def test_project_details(self):
        """
        Test case for project_details

        Public Project
        """
        pass

    def test_projects_list(self):
        """
        Test case for projects_list

        Public Projects
        """
        pass

    def test_projects_search(self):
        """
        Test case for projects_search

        Public Projects Search
        """
        pass


if __name__ == '__main__':
    unittest.main()
