# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.collections_api import CollectionsApi


class TestCollectionsApi(unittest.TestCase):
    """ CollectionsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.collections_api.CollectionsApi()

    def tearDown(self):
        pass

    def test_collection_articles(self):
        """
        Test case for collection_articles

        Public Collection Articles
        """
        pass

    def test_collection_details(self):
        """
        Test case for collection_details

        Collection details
        """
        pass

    def test_collection_version_details(self):
        """
        Test case for collection_version_details

        Collection Version details
        """
        pass

    def test_collection_versions(self):
        """
        Test case for collection_versions

        Collection Versions list
        """
        pass

    def test_collections_list(self):
        """
        Test case for collections_list

        Public Collections
        """
        pass

    def test_collections_search(self):
        """
        Test case for collections_search

        Public Collections Search
        """
        pass

    def test_private_collection_article_delete(self):
        """
        Test case for private_collection_article_delete

        Delete collection article
        """
        pass

    def test_private_collection_articles_add(self):
        """
        Test case for private_collection_articles_add

        Add collection articles
        """
        pass

    def test_private_collection_articles_list(self):
        """
        Test case for private_collection_articles_list

        List collection articles
        """
        pass

    def test_private_collection_articles_replace(self):
        """
        Test case for private_collection_articles_replace

        Replace collection articles
        """
        pass

    def test_private_collection_author_delete(self):
        """
        Test case for private_collection_author_delete

        Delete collection author
        """
        pass

    def test_private_collection_authors_add(self):
        """
        Test case for private_collection_authors_add

        Add collection authors
        """
        pass

    def test_private_collection_authors_list(self):
        """
        Test case for private_collection_authors_list

        List collection authors
        """
        pass

    def test_private_collection_authors_replace(self):
        """
        Test case for private_collection_authors_replace

        Replace collection authors
        """
        pass

    def test_private_collection_categories_add(self):
        """
        Test case for private_collection_categories_add

        Add collection categories
        """
        pass

    def test_private_collection_categories_list(self):
        """
        Test case for private_collection_categories_list

        List collection categories
        """
        pass

    def test_private_collection_categories_replace(self):
        """
        Test case for private_collection_categories_replace

        Replace collection categories
        """
        pass

    def test_private_collection_category_delete(self):
        """
        Test case for private_collection_category_delete

        Delete collection category
        """
        pass

    def test_private_collection_create(self):
        """
        Test case for private_collection_create

        Create collection
        """
        pass

    def test_private_collection_delete(self):
        """
        Test case for private_collection_delete

        Delete collection
        """
        pass

    def test_private_collection_details(self):
        """
        Test case for private_collection_details

        Collection details
        """
        pass

    def test_private_collection_private_link_create(self):
        """
        Test case for private_collection_private_link_create

        Create collection private link
        """
        pass

    def test_private_collection_private_link_delete(self):
        """
        Test case for private_collection_private_link_delete

        Disable private link
        """
        pass

    def test_private_collection_private_link_update(self):
        """
        Test case for private_collection_private_link_update

        Update collection private link
        """
        pass

    def test_private_collection_private_links_list(self):
        """
        Test case for private_collection_private_links_list

        List collection private links
        """
        pass

    def test_private_collection_publish(self):
        """
        Test case for private_collection_publish

        Private Collection Publish
        """
        pass

    def test_private_collection_reserve_doi(self):
        """
        Test case for private_collection_reserve_doi

        Private Collection Reserve DOI
        """
        pass

    def test_private_collection_reserve_handle(self):
        """
        Test case for private_collection_reserve_handle

        Private Collection Reserve Handle
        """
        pass

    def test_private_collection_resource(self):
        """
        Test case for private_collection_resource

        Private Collection Resource
        """
        pass

    def test_private_collection_update(self):
        """
        Test case for private_collection_update

        Update collection
        """
        pass

    def test_private_collections_list(self):
        """
        Test case for private_collections_list

        Private Collections List
        """
        pass

    def test_private_collections_search(self):
        """
        Test case for private_collections_search

        Private Collections Search
        """
        pass


if __name__ == '__main__':
    unittest.main()
