# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.authors_api import AuthorsApi


class TestAuthorsApi(unittest.TestCase):
    """ AuthorsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.authors_api.AuthorsApi()

    def tearDown(self):
        pass

    def test_private_author_details(self):
        """
        Test case for private_author_details

        Author details
        """
        pass

    def test_private_authors_search(self):
        """
        Test case for private_authors_search

        Search Authors
        """
        pass


if __name__ == '__main__':
    unittest.main()
