# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from .account import Account
from .account_create import AccountCreate
from .account_group_roles import AccountGroupRoles
from .account_group_roles_create import AccountGroupRolesCreate
from .account_report import AccountReport
from .account_update import AccountUpdate
from .article import Article
from .article_confidentiality import ArticleConfidentiality
from .article_create import ArticleCreate
from .article_doi import ArticleDOI
from .article_embargo import ArticleEmbargo
from .article_embargo_updater import ArticleEmbargoUpdater
from .article_handle import ArticleHandle
from .article_project_create import ArticleProjectCreate
from .article_update import ArticleUpdate
from .article_versions import ArticleVersions
from .articles_creator import ArticlesCreator
from .author import Author
from .authors_creator import AuthorsCreator
from .categories_creator import CategoriesCreator
from .category import Category
from .collaborator import Collaborator
from .collection import Collection
from .collection_create import CollectionCreate
from .collection_doi import CollectionDOI
from .collection_handle import CollectionHandle
from .collection_private_link_creator import CollectionPrivateLinkCreator
from .collection_update import CollectionUpdate
from .collection_versions import CollectionVersions
from .common_search import CommonSearch
from .confidentiality_creator import ConfidentialityCreator
from .create_project_response import CreateProjectResponse
from .curation import Curation
from .curation_comment import CurationComment
from .curation_comment_create import CurationCommentCreate
from .custom_article_field import CustomArticleField
from .custom_article_field_add import CustomArticleFieldAdd
from .error_message import ErrorMessage
from .file_creator import FileCreator
from .file_id import FileId
from .funding_create import FundingCreate
from .funding_information import FundingInformation
from .funding_search import FundingSearch
from .group import Group
from .group_embargo_options import GroupEmbargoOptions
from .institution import Institution
from .institution_accounts_search import InstitutionAccountsSearch
from .item_type import ItemType
from .license import License
from .location import Location
from .location_warnings import LocationWarnings
from .location_warnings_update import LocationWarningsUpdate
from .private_authors_search import PrivateAuthorsSearch
from .private_link import PrivateLink
from .private_link_creator import PrivateLinkCreator
from .private_link_response import PrivateLinkResponse
from .project import Project
from .project_collaborator import ProjectCollaborator
from .project_collaborator_invite import ProjectCollaboratorInvite
from .project_create import ProjectCreate
from .project_note import ProjectNote
from .project_note_create import ProjectNoteCreate
from .project_update import ProjectUpdate
from .public_file import PublicFile
from .resource import Resource
from .response_message import ResponseMessage
from .role import Role
from .short_account import ShortAccount
from .short_custom_field import ShortCustomField
from .timeline_update import TimelineUpdate
from .upload_file_part import UploadFilePart
from .upload_info import UploadInfo
from .user import User
from .article_search import ArticleSearch
from .article_with_project import ArticleWithProject
from .author_complete import AuthorComplete
from .collection_complete import CollectionComplete
from .collection_complete_private import CollectionCompletePrivate
from .collection_search import CollectionSearch
from .curation_detail import CurationDetail
from .private_file import PrivateFile
from .project_article import ProjectArticle
from .project_complete import ProjectComplete
from .project_note_private import ProjectNotePrivate
from .project_private import ProjectPrivate
from .projects_search import ProjectsSearch
from .timeline import Timeline
from .article_complete import ArticleComplete
from .private_article_search import PrivateArticleSearch
from .private_collection_search import PrivateCollectionSearch
from .project_complete_private import ProjectCompletePrivate
from .article_complete_private import ArticleCompletePrivate
