# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Account(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'first_name': 'str',
        'last_name': 'str',
        'used_quota_private': 'int',
        'modified_date': 'str',
        'used_quota': 'int',
        'created_date': 'str',
        'quota': 'int',
        'group_id': 'int',
        'institution_user_id': 'str',
        'institution_id': 'int',
        'email': 'str',
        'used_quota_public': 'int',
        'pending_quota_request': 'bool',
        'active': 'int',
        'maximum_file_size': 'int'
    }

    attribute_map = {
        'id': 'id',
        'first_name': 'first_name',
        'last_name': 'last_name',
        'used_quota_private': 'used_quota_private',
        'modified_date': 'modified_date',
        'used_quota': 'used_quota',
        'created_date': 'created_date',
        'quota': 'quota',
        'group_id': 'group_id',
        'institution_user_id': 'institution_user_id',
        'institution_id': 'institution_id',
        'email': 'email',
        'used_quota_public': 'used_quota_public',
        'pending_quota_request': 'pending_quota_request',
        'active': 'active',
        'maximum_file_size': 'maximum_file_size'
    }

    def __init__(self, id=None, first_name=None, last_name=None, used_quota_private=None, modified_date=None, used_quota=None, created_date=None, quota=None, group_id=None, institution_user_id=None, institution_id=None, email=None, used_quota_public=None, pending_quota_request=None, active=None, maximum_file_size=None):
        """
        Account - a model defined in Swagger
        """

        self._id = None
        self._first_name = None
        self._last_name = None
        self._used_quota_private = None
        self._modified_date = None
        self._used_quota = None
        self._created_date = None
        self._quota = None
        self._group_id = None
        self._institution_user_id = None
        self._institution_id = None
        self._email = None
        self._used_quota_public = None
        self._pending_quota_request = None
        self._active = None
        self._maximum_file_size = None

        self.id = id
        self.first_name = first_name
        self.last_name = last_name
        self.used_quota_private = used_quota_private
        self.modified_date = modified_date
        self.used_quota = used_quota
        self.created_date = created_date
        self.quota = quota
        self.group_id = group_id
        self.institution_user_id = institution_user_id
        self.institution_id = institution_id
        self.email = email
        self.used_quota_public = used_quota_public
        self.pending_quota_request = pending_quota_request
        self.active = active
        self.maximum_file_size = maximum_file_size

    @property
    def id(self):
        """
        Gets the id of this Account.
        Account id

        :return: The id of this Account.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Account.
        Account id

        :param id: The id of this Account.
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def first_name(self):
        """
        Gets the first_name of this Account.
        First Name

        :return: The first_name of this Account.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """
        Sets the first_name of this Account.
        First Name

        :param first_name: The first_name of this Account.
        :type: str
        """
        if first_name is None:
            raise ValueError("Invalid value for `first_name`, must not be `None`")

        self._first_name = first_name

    @property
    def last_name(self):
        """
        Gets the last_name of this Account.
        Last Name

        :return: The last_name of this Account.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """
        Sets the last_name of this Account.
        Last Name

        :param last_name: The last_name of this Account.
        :type: str
        """
        if last_name is None:
            raise ValueError("Invalid value for `last_name`, must not be `None`")

        self._last_name = last_name

    @property
    def used_quota_private(self):
        """
        Gets the used_quota_private of this Account.
        Account used private quota

        :return: The used_quota_private of this Account.
        :rtype: int
        """
        return self._used_quota_private

    @used_quota_private.setter
    def used_quota_private(self, used_quota_private):
        """
        Sets the used_quota_private of this Account.
        Account used private quota

        :param used_quota_private: The used_quota_private of this Account.
        :type: int
        """
        if used_quota_private is None:
            raise ValueError("Invalid value for `used_quota_private`, must not be `None`")

        self._used_quota_private = used_quota_private

    @property
    def modified_date(self):
        """
        Gets the modified_date of this Account.
        Date of last account modification

        :return: The modified_date of this Account.
        :rtype: str
        """
        return self._modified_date

    @modified_date.setter
    def modified_date(self, modified_date):
        """
        Sets the modified_date of this Account.
        Date of last account modification

        :param modified_date: The modified_date of this Account.
        :type: str
        """
        if modified_date is None:
            raise ValueError("Invalid value for `modified_date`, must not be `None`")

        self._modified_date = modified_date

    @property
    def used_quota(self):
        """
        Gets the used_quota of this Account.
        Account total used quota

        :return: The used_quota of this Account.
        :rtype: int
        """
        return self._used_quota

    @used_quota.setter
    def used_quota(self, used_quota):
        """
        Sets the used_quota of this Account.
        Account total used quota

        :param used_quota: The used_quota of this Account.
        :type: int
        """
        if used_quota is None:
            raise ValueError("Invalid value for `used_quota`, must not be `None`")

        self._used_quota = used_quota

    @property
    def created_date(self):
        """
        Gets the created_date of this Account.
        Date when account was created

        :return: The created_date of this Account.
        :rtype: str
        """
        return self._created_date

    @created_date.setter
    def created_date(self, created_date):
        """
        Sets the created_date of this Account.
        Date when account was created

        :param created_date: The created_date of this Account.
        :type: str
        """
        if created_date is None:
            raise ValueError("Invalid value for `created_date`, must not be `None`")

        self._created_date = created_date

    @property
    def quota(self):
        """
        Gets the quota of this Account.
        Account quota

        :return: The quota of this Account.
        :rtype: int
        """
        return self._quota

    @quota.setter
    def quota(self, quota):
        """
        Sets the quota of this Account.
        Account quota

        :param quota: The quota of this Account.
        :type: int
        """
        if quota is None:
            raise ValueError("Invalid value for `quota`, must not be `None`")

        self._quota = quota

    @property
    def group_id(self):
        """
        Gets the group_id of this Account.
        Account group id

        :return: The group_id of this Account.
        :rtype: int
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """
        Sets the group_id of this Account.
        Account group id

        :param group_id: The group_id of this Account.
        :type: int
        """
        if group_id is None:
            raise ValueError("Invalid value for `group_id`, must not be `None`")

        self._group_id = group_id

    @property
    def institution_user_id(self):
        """
        Gets the institution_user_id of this Account.
        Account institution user id

        :return: The institution_user_id of this Account.
        :rtype: str
        """
        return self._institution_user_id

    @institution_user_id.setter
    def institution_user_id(self, institution_user_id):
        """
        Sets the institution_user_id of this Account.
        Account institution user id

        :param institution_user_id: The institution_user_id of this Account.
        :type: str
        """
        if institution_user_id is None:
            raise ValueError("Invalid value for `institution_user_id`, must not be `None`")

        self._institution_user_id = institution_user_id

    @property
    def institution_id(self):
        """
        Gets the institution_id of this Account.
        Account institution

        :return: The institution_id of this Account.
        :rtype: int
        """
        return self._institution_id

    @institution_id.setter
    def institution_id(self, institution_id):
        """
        Sets the institution_id of this Account.
        Account institution

        :param institution_id: The institution_id of this Account.
        :type: int
        """
        if institution_id is None:
            raise ValueError("Invalid value for `institution_id`, must not be `None`")

        self._institution_id = institution_id

    @property
    def email(self):
        """
        Gets the email of this Account.
        User email

        :return: The email of this Account.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """
        Sets the email of this Account.
        User email

        :param email: The email of this Account.
        :type: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")

        self._email = email

    @property
    def used_quota_public(self):
        """
        Gets the used_quota_public of this Account.
        Account public used quota

        :return: The used_quota_public of this Account.
        :rtype: int
        """
        return self._used_quota_public

    @used_quota_public.setter
    def used_quota_public(self, used_quota_public):
        """
        Sets the used_quota_public of this Account.
        Account public used quota

        :param used_quota_public: The used_quota_public of this Account.
        :type: int
        """
        if used_quota_public is None:
            raise ValueError("Invalid value for `used_quota_public`, must not be `None`")

        self._used_quota_public = used_quota_public

    @property
    def pending_quota_request(self):
        """
        Gets the pending_quota_request of this Account.
        True if a quota request is pending

        :return: The pending_quota_request of this Account.
        :rtype: bool
        """
        return self._pending_quota_request

    @pending_quota_request.setter
    def pending_quota_request(self, pending_quota_request):
        """
        Sets the pending_quota_request of this Account.
        True if a quota request is pending

        :param pending_quota_request: The pending_quota_request of this Account.
        :type: bool
        """
        if pending_quota_request is None:
            raise ValueError("Invalid value for `pending_quota_request`, must not be `None`")

        self._pending_quota_request = pending_quota_request

    @property
    def active(self):
        """
        Gets the active of this Account.
        Account activity status

        :return: The active of this Account.
        :rtype: int
        """
        return self._active

    @active.setter
    def active(self, active):
        """
        Sets the active of this Account.
        Account activity status

        :param active: The active of this Account.
        :type: int
        """
        if active is None:
            raise ValueError("Invalid value for `active`, must not be `None`")

        self._active = active

    @property
    def maximum_file_size(self):
        """
        Gets the maximum_file_size of this Account.
        Maximum upload size for account

        :return: The maximum_file_size of this Account.
        :rtype: int
        """
        return self._maximum_file_size

    @maximum_file_size.setter
    def maximum_file_size(self, maximum_file_size):
        """
        Sets the maximum_file_size of this Account.
        Maximum upload size for account

        :param maximum_file_size: The maximum_file_size of this Account.
        :type: int
        """
        if maximum_file_size is None:
            raise ValueError("Invalid value for `maximum_file_size`, must not be `None`")

        self._maximum_file_size = maximum_file_size

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Account):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
