# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ArticleEmbargoUpdater(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_embargoed': 'bool',
        'embargo_date': 'str',
        'embargo_type': 'str',
        'embargo_title': 'str',
        'embargo_reason': 'str',
        'embargo_options': 'list[object]'
    }

    attribute_map = {
        'is_embargoed': 'is_embargoed',
        'embargo_date': 'embargo_date',
        'embargo_type': 'embargo_type',
        'embargo_title': 'embargo_title',
        'embargo_reason': 'embargo_reason',
        'embargo_options': 'embargo_options'
    }

    def __init__(self, is_embargoed=None, embargo_date=None, embargo_type=None, embargo_title=None, embargo_reason=None, embargo_options=None):
        """
        ArticleEmbargoUpdater - a model defined in Swagger
        """

        self._is_embargoed = None
        self._embargo_date = None
        self._embargo_type = None
        self._embargo_title = None
        self._embargo_reason = None
        self._embargo_options = None

        self.is_embargoed = is_embargoed
        self.embargo_date = embargo_date
        self.embargo_type = embargo_type
        if embargo_title is not None:
          self.embargo_title = embargo_title
        if embargo_reason is not None:
          self.embargo_reason = embargo_reason
        if embargo_options is not None:
          self.embargo_options = embargo_options

    @property
    def is_embargoed(self):
        """
        Gets the is_embargoed of this ArticleEmbargoUpdater.
        Embargo status

        :return: The is_embargoed of this ArticleEmbargoUpdater.
        :rtype: bool
        """
        return self._is_embargoed

    @is_embargoed.setter
    def is_embargoed(self, is_embargoed):
        """
        Sets the is_embargoed of this ArticleEmbargoUpdater.
        Embargo status

        :param is_embargoed: The is_embargoed of this ArticleEmbargoUpdater.
        :type: bool
        """
        if is_embargoed is None:
            raise ValueError("Invalid value for `is_embargoed`, must not be `None`")

        self._is_embargoed = is_embargoed

    @property
    def embargo_date(self):
        """
        Gets the embargo_date of this ArticleEmbargoUpdater.
        Date when the embargo expires and the article gets published, '0' value will set up permanent embargo

        :return: The embargo_date of this ArticleEmbargoUpdater.
        :rtype: str
        """
        return self._embargo_date

    @embargo_date.setter
    def embargo_date(self, embargo_date):
        """
        Sets the embargo_date of this ArticleEmbargoUpdater.
        Date when the embargo expires and the article gets published, '0' value will set up permanent embargo

        :param embargo_date: The embargo_date of this ArticleEmbargoUpdater.
        :type: str
        """
        if embargo_date is None:
            raise ValueError("Invalid value for `embargo_date`, must not be `None`")

        self._embargo_date = embargo_date

    @property
    def embargo_type(self):
        """
        Gets the embargo_type of this ArticleEmbargoUpdater.
        Embargo can be enabled at the article or the file level. Possible values: article, file

        :return: The embargo_type of this ArticleEmbargoUpdater.
        :rtype: str
        """
        return self._embargo_type

    @embargo_type.setter
    def embargo_type(self, embargo_type):
        """
        Sets the embargo_type of this ArticleEmbargoUpdater.
        Embargo can be enabled at the article or the file level. Possible values: article, file

        :param embargo_type: The embargo_type of this ArticleEmbargoUpdater.
        :type: str
        """
        if embargo_type is None:
            raise ValueError("Invalid value for `embargo_type`, must not be `None`")
        allowed_values = ["article", "file"]
        if embargo_type not in allowed_values:
            raise ValueError(
                "Invalid value for `embargo_type` ({0}), must be one of {1}"
                .format(embargo_type, allowed_values)
            )

        self._embargo_type = embargo_type

    @property
    def embargo_title(self):
        """
        Gets the embargo_title of this ArticleEmbargoUpdater.
        Title for embargo

        :return: The embargo_title of this ArticleEmbargoUpdater.
        :rtype: str
        """
        return self._embargo_title

    @embargo_title.setter
    def embargo_title(self, embargo_title):
        """
        Sets the embargo_title of this ArticleEmbargoUpdater.
        Title for embargo

        :param embargo_title: The embargo_title of this ArticleEmbargoUpdater.
        :type: str
        """

        self._embargo_title = embargo_title

    @property
    def embargo_reason(self):
        """
        Gets the embargo_reason of this ArticleEmbargoUpdater.
        Reason for setting embargo

        :return: The embargo_reason of this ArticleEmbargoUpdater.
        :rtype: str
        """
        return self._embargo_reason

    @embargo_reason.setter
    def embargo_reason(self, embargo_reason):
        """
        Sets the embargo_reason of this ArticleEmbargoUpdater.
        Reason for setting embargo

        :param embargo_reason: The embargo_reason of this ArticleEmbargoUpdater.
        :type: str
        """

        self._embargo_reason = embargo_reason

    @property
    def embargo_options(self):
        """
        Gets the embargo_options of this ArticleEmbargoUpdater.
        List of embargo permissions to be associated with the article. The list must contain `id` and can also contain `group_ids`(a field that only applies to 'logged_in' permissions). The new list replaces old options in the database, and an empty list removes all permissions for this article. Administration permission has to be set up alone but logged in and IP range permissions can be set up together.

        :return: The embargo_options of this ArticleEmbargoUpdater.
        :rtype: list[object]
        """
        return self._embargo_options

    @embargo_options.setter
    def embargo_options(self, embargo_options):
        """
        Sets the embargo_options of this ArticleEmbargoUpdater.
        List of embargo permissions to be associated with the article. The list must contain `id` and can also contain `group_ids`(a field that only applies to 'logged_in' permissions). The new list replaces old options in the database, and an empty list removes all permissions for this article. Administration permission has to be set up alone but logged in and IP range permissions can be set up together.

        :param embargo_options: The embargo_options of this ArticleEmbargoUpdater.
        :type: list[object]
        """

        self._embargo_options = embargo_options

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ArticleEmbargoUpdater):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
