# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ArticleEmbargo(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_embargoed': 'bool',
        'embargo_title': 'str',
        'embargo_reason': 'str',
        'embargo_options': 'list[object]'
    }

    attribute_map = {
        'is_embargoed': 'is_embargoed',
        'embargo_title': 'embargo_title',
        'embargo_reason': 'embargo_reason',
        'embargo_options': 'embargo_options'
    }

    def __init__(self, is_embargoed=None, embargo_title=None, embargo_reason=None, embargo_options=None):
        """
        ArticleEmbargo - a model defined in Swagger
        """

        self._is_embargoed = None
        self._embargo_title = None
        self._embargo_reason = None
        self._embargo_options = None

        self.is_embargoed = is_embargoed
        self.embargo_title = embargo_title
        self.embargo_reason = embargo_reason
        self.embargo_options = embargo_options

    @property
    def is_embargoed(self):
        """
        Gets the is_embargoed of this ArticleEmbargo.
        True if embargoed

        :return: The is_embargoed of this ArticleEmbargo.
        :rtype: bool
        """
        return self._is_embargoed

    @is_embargoed.setter
    def is_embargoed(self, is_embargoed):
        """
        Sets the is_embargoed of this ArticleEmbargo.
        True if embargoed

        :param is_embargoed: The is_embargoed of this ArticleEmbargo.
        :type: bool
        """
        if is_embargoed is None:
            raise ValueError("Invalid value for `is_embargoed`, must not be `None`")

        self._is_embargoed = is_embargoed

    @property
    def embargo_title(self):
        """
        Gets the embargo_title of this ArticleEmbargo.
        Title for embargo

        :return: The embargo_title of this ArticleEmbargo.
        :rtype: str
        """
        return self._embargo_title

    @embargo_title.setter
    def embargo_title(self, embargo_title):
        """
        Sets the embargo_title of this ArticleEmbargo.
        Title for embargo

        :param embargo_title: The embargo_title of this ArticleEmbargo.
        :type: str
        """
        if embargo_title is None:
            raise ValueError("Invalid value for `embargo_title`, must not be `None`")

        self._embargo_title = embargo_title

    @property
    def embargo_reason(self):
        """
        Gets the embargo_reason of this ArticleEmbargo.
        Reason for embargo

        :return: The embargo_reason of this ArticleEmbargo.
        :rtype: str
        """
        return self._embargo_reason

    @embargo_reason.setter
    def embargo_reason(self, embargo_reason):
        """
        Sets the embargo_reason of this ArticleEmbargo.
        Reason for embargo

        :param embargo_reason: The embargo_reason of this ArticleEmbargo.
        :type: str
        """
        if embargo_reason is None:
            raise ValueError("Invalid value for `embargo_reason`, must not be `None`")

        self._embargo_reason = embargo_reason

    @property
    def embargo_options(self):
        """
        Gets the embargo_options of this ArticleEmbargo.
        List of embargo permissions that are associated with the article. If the type is logged_in and the group_ids list is empty, then the whole institution can see the article; if there are multiple group_ids, then only users that are under those groups can see the article.

        :return: The embargo_options of this ArticleEmbargo.
        :rtype: list[object]
        """
        return self._embargo_options

    @embargo_options.setter
    def embargo_options(self, embargo_options):
        """
        Sets the embargo_options of this ArticleEmbargo.
        List of embargo permissions that are associated with the article. If the type is logged_in and the group_ids list is empty, then the whole institution can see the article; if there are multiple group_ids, then only users that are under those groups can see the article.

        :param embargo_options: The embargo_options of this ArticleEmbargo.
        :type: list[object]
        """
        if embargo_options is None:
            raise ValueError("Invalid value for `embargo_options`, must not be `None`")

        self._embargo_options = embargo_options

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ArticleEmbargo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
