# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ArticleConfidentiality(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_confidential': 'bool',
        'reason': 'str'
    }

    attribute_map = {
        'is_confidential': 'is_confidential',
        'reason': 'reason'
    }

    def __init__(self, is_confidential=None, reason=None):
        """
        ArticleConfidentiality - a model defined in Swagger
        """

        self._is_confidential = None
        self._reason = None

        self.is_confidential = is_confidential
        self.reason = reason

    @property
    def is_confidential(self):
        """
        Gets the is_confidential of this ArticleConfidentiality.
        True if article is confidential

        :return: The is_confidential of this ArticleConfidentiality.
        :rtype: bool
        """
        return self._is_confidential

    @is_confidential.setter
    def is_confidential(self, is_confidential):
        """
        Sets the is_confidential of this ArticleConfidentiality.
        True if article is confidential

        :param is_confidential: The is_confidential of this ArticleConfidentiality.
        :type: bool
        """
        if is_confidential is None:
            raise ValueError("Invalid value for `is_confidential`, must not be `None`")

        self._is_confidential = is_confidential

    @property
    def reason(self):
        """
        Gets the reason of this ArticleConfidentiality.
        Reason for confidentiality

        :return: The reason of this ArticleConfidentiality.
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """
        Sets the reason of this ArticleConfidentiality.
        Reason for confidentiality

        :param reason: The reason of this ArticleConfidentiality.
        :type: str
        """
        if reason is None:
            raise ValueError("Invalid value for `reason`, must not be `None`")

        self._reason = reason

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ArticleConfidentiality):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
