# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class CollectionComplete(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'title': 'str',
        'doi': 'str',
        'handle': 'str',
        'url': 'str',
        'timeline': 'Timeline'
    }

    attribute_map = {
        'id': 'id',
        'title': 'title',
        'doi': 'doi',
        'handle': 'handle',
        'url': 'url',
        'timeline': 'timeline'
    }

    def __init__(self, id=None, title=None, doi=None, handle=None, url=None, timeline=None):
        """
        CollectionComplete - a model defined in Swagger
        """

        self._id = None
        self._title = None
        self._doi = None
        self._handle = None
        self._url = None
        self._timeline = None

        self.id = id
        self.title = title
        self.doi = doi
        self.handle = handle
        self.url = url
        self.timeline = timeline

    @property
    def id(self):
        """
        Gets the id of this CollectionComplete.
        Collection id

        :return: The id of this CollectionComplete.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this CollectionComplete.
        Collection id

        :param id: The id of this CollectionComplete.
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def title(self):
        """
        Gets the title of this CollectionComplete.
        Collection title

        :return: The title of this CollectionComplete.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """
        Sets the title of this CollectionComplete.
        Collection title

        :param title: The title of this CollectionComplete.
        :type: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")

        self._title = title

    @property
    def doi(self):
        """
        Gets the doi of this CollectionComplete.
        Collection DOI

        :return: The doi of this CollectionComplete.
        :rtype: str
        """
        return self._doi

    @doi.setter
    def doi(self, doi):
        """
        Sets the doi of this CollectionComplete.
        Collection DOI

        :param doi: The doi of this CollectionComplete.
        :type: str
        """
        if doi is None:
            raise ValueError("Invalid value for `doi`, must not be `None`")

        self._doi = doi

    @property
    def handle(self):
        """
        Gets the handle of this CollectionComplete.
        Collection Handle

        :return: The handle of this CollectionComplete.
        :rtype: str
        """
        return self._handle

    @handle.setter
    def handle(self, handle):
        """
        Sets the handle of this CollectionComplete.
        Collection Handle

        :param handle: The handle of this CollectionComplete.
        :type: str
        """
        if handle is None:
            raise ValueError("Invalid value for `handle`, must not be `None`")

        self._handle = handle

    @property
    def url(self):
        """
        Gets the url of this CollectionComplete.
        Api endpoint

        :return: The url of this CollectionComplete.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """
        Sets the url of this CollectionComplete.
        Api endpoint

        :param url: The url of this CollectionComplete.
        :type: str
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")

        self._url = url

    @property
    def timeline(self):
        """
        Gets the timeline of this CollectionComplete.
        Various timeline dates

        :return: The timeline of this CollectionComplete.
        :rtype: Timeline
        """
        return self._timeline

    @timeline.setter
    def timeline(self, timeline):
        """
        Sets the timeline of this CollectionComplete.
        Various timeline dates

        :param timeline: The timeline of this CollectionComplete.
        :type: Timeline
        """
        if timeline is None:
            raise ValueError("Invalid value for `timeline`, must not be `None`")

        self._timeline = timeline

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CollectionComplete):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
