# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class GroupEmbargoOptions(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'type': 'str',
        'ip_name': 'str'
    }

    attribute_map = {
        'id': 'id',
        'type': 'type',
        'ip_name': 'ip_name'
    }

    def __init__(self, id=None, type=None, ip_name=None):
        """
        GroupEmbargoOptions - a model defined in Swagger
        """

        self._id = None
        self._type = None
        self._ip_name = None

        self.id = id
        self.type = type
        self.ip_name = ip_name

    @property
    def id(self):
        """
        Gets the id of this GroupEmbargoOptions.
        Embargo option id

        :return: The id of this GroupEmbargoOptions.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this GroupEmbargoOptions.
        Embargo option id

        :param id: The id of this GroupEmbargoOptions.
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def type(self):
        """
        Gets the type of this GroupEmbargoOptions.
        Embargo permission type

        :return: The type of this GroupEmbargoOptions.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this GroupEmbargoOptions.
        Embargo permission type

        :param type: The type of this GroupEmbargoOptions.
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")
        allowed_values = ["logged_in", "ip_range", "administrator"]
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def ip_name(self):
        """
        Gets the ip_name of this GroupEmbargoOptions.
        IP range name; value appears if type is ip_range

        :return: The ip_name of this GroupEmbargoOptions.
        :rtype: str
        """
        return self._ip_name

    @ip_name.setter
    def ip_name(self, ip_name):
        """
        Sets the ip_name of this GroupEmbargoOptions.
        IP range name; value appears if type is ip_range

        :param ip_name: The ip_name of this GroupEmbargoOptions.
        :type: str
        """
        if ip_name is None:
            raise ValueError("Invalid value for `ip_name`, must not be `None`")

        self._ip_name = ip_name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, GroupEmbargoOptions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
