# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ItemType(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'string_id': 'str',
        'icon': 'str',
        'public_description': 'str',
        'is_selectable': 'bool',
        'url_name': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'string_id': 'string_id',
        'icon': 'icon',
        'public_description': 'public_description',
        'is_selectable': 'is_selectable',
        'url_name': 'url_name'
    }

    def __init__(self, id=None, name=None, string_id=None, icon=None, public_description=None, is_selectable=None, url_name=None):
        """
        ItemType - a model defined in Swagger
        """

        self._id = None
        self._name = None
        self._string_id = None
        self._icon = None
        self._public_description = None
        self._is_selectable = None
        self._url_name = None

        self.id = id
        self.name = name
        self.string_id = string_id
        self.icon = icon
        self.public_description = public_description
        self.is_selectable = is_selectable
        self.url_name = url_name

    @property
    def id(self):
        """
        Gets the id of this ItemType.
        The ID of the item type.

        :return: The id of this ItemType.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this ItemType.
        The ID of the item type.

        :param id: The id of this ItemType.
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")
        if id is not None and id < 1:
            raise ValueError("Invalid value for `id`, must be a value greater than or equal to `1`")

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this ItemType.
        The name of the item type

        :return: The name of this ItemType.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this ItemType.
        The name of the item type

        :param name: The name of this ItemType.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def string_id(self):
        """
        Gets the string_id of this ItemType.
        The string identifier of the item type.

        :return: The string_id of this ItemType.
        :rtype: str
        """
        return self._string_id

    @string_id.setter
    def string_id(self, string_id):
        """
        Sets the string_id of this ItemType.
        The string identifier of the item type.

        :param string_id: The string_id of this ItemType.
        :type: str
        """
        if string_id is None:
            raise ValueError("Invalid value for `string_id`, must not be `None`")

        self._string_id = string_id

    @property
    def icon(self):
        """
        Gets the icon of this ItemType.
        The string identifying the icon of the item type.

        :return: The icon of this ItemType.
        :rtype: str
        """
        return self._icon

    @icon.setter
    def icon(self, icon):
        """
        Sets the icon of this ItemType.
        The string identifying the icon of the item type.

        :param icon: The icon of this ItemType.
        :type: str
        """
        if icon is None:
            raise ValueError("Invalid value for `icon`, must not be `None`")

        self._icon = icon

    @property
    def public_description(self):
        """
        Gets the public_description of this ItemType.
        The description of the item type.

        :return: The public_description of this ItemType.
        :rtype: str
        """
        return self._public_description

    @public_description.setter
    def public_description(self, public_description):
        """
        Sets the public_description of this ItemType.
        The description of the item type.

        :param public_description: The public_description of this ItemType.
        :type: str
        """
        if public_description is None:
            raise ValueError("Invalid value for `public_description`, must not be `None`")

        self._public_description = public_description

    @property
    def is_selectable(self):
        """
        Gets the is_selectable of this ItemType.
        The selectable status

        :return: The is_selectable of this ItemType.
        :rtype: bool
        """
        return self._is_selectable

    @is_selectable.setter
    def is_selectable(self, is_selectable):
        """
        Sets the is_selectable of this ItemType.
        The selectable status

        :param is_selectable: The is_selectable of this ItemType.
        :type: bool
        """
        if is_selectable is None:
            raise ValueError("Invalid value for `is_selectable`, must not be `None`")

        self._is_selectable = is_selectable

    @property
    def url_name(self):
        """
        Gets the url_name of this ItemType.
        The URL name of the item type.

        :return: The url_name of this ItemType.
        :rtype: str
        """
        return self._url_name

    @url_name.setter
    def url_name(self, url_name):
        """
        Sets the url_name of this ItemType.
        The URL name of the item type.

        :param url_name: The url_name of this ItemType.
        :type: str
        """
        if url_name is None:
            raise ValueError("Invalid value for `url_name`, must not be `None`")

        self._url_name = url_name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ItemType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
