# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PrivateLinkResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'location': 'str',
        'html_location': 'str',
        'token': 'str'
    }

    attribute_map = {
        'location': 'location',
        'html_location': 'html_location',
        'token': 'token'
    }

    def __init__(self, location=None, html_location=None, token=None):
        """
        PrivateLinkResponse - a model defined in Swagger
        """

        self._location = None
        self._html_location = None
        self._token = None

        self.location = location
        self.html_location = html_location
        self.token = token

    @property
    def location(self):
        """
        Gets the location of this PrivateLinkResponse.
        Url for private link

        :return: The location of this PrivateLinkResponse.
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location):
        """
        Sets the location of this PrivateLinkResponse.
        Url for private link

        :param location: The location of this PrivateLinkResponse.
        :type: str
        """
        if location is None:
            raise ValueError("Invalid value for `location`, must not be `None`")

        self._location = location

    @property
    def html_location(self):
        """
        Gets the html_location of this PrivateLinkResponse.
        HTML url for private link

        :return: The html_location of this PrivateLinkResponse.
        :rtype: str
        """
        return self._html_location

    @html_location.setter
    def html_location(self, html_location):
        """
        Sets the html_location of this PrivateLinkResponse.
        HTML url for private link

        :param html_location: The html_location of this PrivateLinkResponse.
        :type: str
        """
        if html_location is None:
            raise ValueError("Invalid value for `html_location`, must not be `None`")

        self._html_location = html_location

    @property
    def token(self):
        """
        Gets the token of this PrivateLinkResponse.
        Token for private link

        :return: The token of this PrivateLinkResponse.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """
        Sets the token of this PrivateLinkResponse.
        Token for private link

        :param token: The token of this PrivateLinkResponse.
        :type: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")

        self._token = token

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PrivateLinkResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
