# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PrivateAuthorsSearch(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'search_for': 'str',
        'page': 'int',
        'page_size': 'int',
        'limit': 'int',
        'offset': 'int',
        'order': 'str',
        'order_direction': 'str',
        'institution_id': 'int',
        'orcid': 'str',
        'group_id': 'int',
        'is_active': 'bool',
        'is_public': 'bool'
    }

    attribute_map = {
        'search_for': 'search_for',
        'page': 'page',
        'page_size': 'page_size',
        'limit': 'limit',
        'offset': 'offset',
        'order': 'order',
        'order_direction': 'order_direction',
        'institution_id': 'institution_id',
        'orcid': 'orcid',
        'group_id': 'group_id',
        'is_active': 'is_active',
        'is_public': 'is_public'
    }

    def __init__(self, search_for=None, page=None, page_size=10, limit=None, offset=None, order='published_date', order_direction='desc', institution_id=None, orcid=None, group_id=None, is_active=None, is_public=None):
        """
        PrivateAuthorsSearch - a model defined in Swagger
        """

        self._search_for = None
        self._page = None
        self._page_size = None
        self._limit = None
        self._offset = None
        self._order = None
        self._order_direction = None
        self._institution_id = None
        self._orcid = None
        self._group_id = None
        self._is_active = None
        self._is_public = None

        if search_for is not None:
          self.search_for = search_for
        if page is not None:
          self.page = page
        if page_size is not None:
          self.page_size = page_size
        if limit is not None:
          self.limit = limit
        if offset is not None:
          self.offset = offset
        if order is not None:
          self.order = order
        if order_direction is not None:
          self.order_direction = order_direction
        if institution_id is not None:
          self.institution_id = institution_id
        if orcid is not None:
          self.orcid = orcid
        if group_id is not None:
          self.group_id = group_id
        if is_active is not None:
          self.is_active = is_active
        if is_public is not None:
          self.is_public = is_public

    @property
    def search_for(self):
        """
        Gets the search_for of this PrivateAuthorsSearch.
        Search term

        :return: The search_for of this PrivateAuthorsSearch.
        :rtype: str
        """
        return self._search_for

    @search_for.setter
    def search_for(self, search_for):
        """
        Sets the search_for of this PrivateAuthorsSearch.
        Search term

        :param search_for: The search_for of this PrivateAuthorsSearch.
        :type: str
        """

        self._search_for = search_for

    @property
    def page(self):
        """
        Gets the page of this PrivateAuthorsSearch.
        Page number. Used for pagination with page_size

        :return: The page of this PrivateAuthorsSearch.
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page):
        """
        Sets the page of this PrivateAuthorsSearch.
        Page number. Used for pagination with page_size

        :param page: The page of this PrivateAuthorsSearch.
        :type: int
        """
        if page is not None and page > 5000:
            raise ValueError("Invalid value for `page`, must be a value less than or equal to `5000`")
        if page is not None and page < 1:
            raise ValueError("Invalid value for `page`, must be a value greater than or equal to `1`")

        self._page = page

    @property
    def page_size(self):
        """
        Gets the page_size of this PrivateAuthorsSearch.
        The number of results included on a page. Used for pagination with page

        :return: The page_size of this PrivateAuthorsSearch.
        :rtype: int
        """
        return self._page_size

    @page_size.setter
    def page_size(self, page_size):
        """
        Sets the page_size of this PrivateAuthorsSearch.
        The number of results included on a page. Used for pagination with page

        :param page_size: The page_size of this PrivateAuthorsSearch.
        :type: int
        """
        if page_size is not None and page_size > 1000:
            raise ValueError("Invalid value for `page_size`, must be a value less than or equal to `1000`")
        if page_size is not None and page_size < 1:
            raise ValueError("Invalid value for `page_size`, must be a value greater than or equal to `1`")

        self._page_size = page_size

    @property
    def limit(self):
        """
        Gets the limit of this PrivateAuthorsSearch.
        Number of results included on a page. Used for pagination with query

        :return: The limit of this PrivateAuthorsSearch.
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """
        Sets the limit of this PrivateAuthorsSearch.
        Number of results included on a page. Used for pagination with query

        :param limit: The limit of this PrivateAuthorsSearch.
        :type: int
        """
        if limit is not None and limit > 1000:
            raise ValueError("Invalid value for `limit`, must be a value less than or equal to `1000`")
        if limit is not None and limit < 1:
            raise ValueError("Invalid value for `limit`, must be a value greater than or equal to `1`")

        self._limit = limit

    @property
    def offset(self):
        """
        Gets the offset of this PrivateAuthorsSearch.
        Where to start the listing(the offset of the first result). Used for pagination with limit

        :return: The offset of this PrivateAuthorsSearch.
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """
        Sets the offset of this PrivateAuthorsSearch.
        Where to start the listing(the offset of the first result). Used for pagination with limit

        :param offset: The offset of this PrivateAuthorsSearch.
        :type: int
        """
        if offset is not None and offset > 5000:
            raise ValueError("Invalid value for `offset`, must be a value less than or equal to `5000`")
        if offset is not None and offset < 0:
            raise ValueError("Invalid value for `offset`, must be a value greater than or equal to `0`")

        self._offset = offset

    @property
    def order(self):
        """
        Gets the order of this PrivateAuthorsSearch.
        The field by which to order. Default varies by endpoint/resource.

        :return: The order of this PrivateAuthorsSearch.
        :rtype: str
        """
        return self._order

    @order.setter
    def order(self, order):
        """
        Sets the order of this PrivateAuthorsSearch.
        The field by which to order. Default varies by endpoint/resource.

        :param order: The order of this PrivateAuthorsSearch.
        :type: str
        """
        allowed_values = ["published_date", "modified_date", "views", "shares", "downloads", "cites"]
        if order not in allowed_values:
            raise ValueError(
                "Invalid value for `order` ({0}), must be one of {1}"
                .format(order, allowed_values)
            )

        self._order = order

    @property
    def order_direction(self):
        """
        Gets the order_direction of this PrivateAuthorsSearch.
        Direction of ordering

        :return: The order_direction of this PrivateAuthorsSearch.
        :rtype: str
        """
        return self._order_direction

    @order_direction.setter
    def order_direction(self, order_direction):
        """
        Sets the order_direction of this PrivateAuthorsSearch.
        Direction of ordering

        :param order_direction: The order_direction of this PrivateAuthorsSearch.
        :type: str
        """
        allowed_values = ["asc", "desc"]
        if order_direction not in allowed_values:
            raise ValueError(
                "Invalid value for `order_direction` ({0}), must be one of {1}"
                .format(order_direction, allowed_values)
            )

        self._order_direction = order_direction

    @property
    def institution_id(self):
        """
        Gets the institution_id of this PrivateAuthorsSearch.
        Return only authors associated to this institution

        :return: The institution_id of this PrivateAuthorsSearch.
        :rtype: int
        """
        return self._institution_id

    @institution_id.setter
    def institution_id(self, institution_id):
        """
        Sets the institution_id of this PrivateAuthorsSearch.
        Return only authors associated to this institution

        :param institution_id: The institution_id of this PrivateAuthorsSearch.
        :type: int
        """

        self._institution_id = institution_id

    @property
    def orcid(self):
        """
        Gets the orcid of this PrivateAuthorsSearch.
        Orcid of author

        :return: The orcid of this PrivateAuthorsSearch.
        :rtype: str
        """
        return self._orcid

    @orcid.setter
    def orcid(self, orcid):
        """
        Sets the orcid of this PrivateAuthorsSearch.
        Orcid of author

        :param orcid: The orcid of this PrivateAuthorsSearch.
        :type: str
        """

        self._orcid = orcid

    @property
    def group_id(self):
        """
        Gets the group_id of this PrivateAuthorsSearch.
        Return only authors in this group or subgroups of the group

        :return: The group_id of this PrivateAuthorsSearch.
        :rtype: int
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """
        Sets the group_id of this PrivateAuthorsSearch.
        Return only authors in this group or subgroups of the group

        :param group_id: The group_id of this PrivateAuthorsSearch.
        :type: int
        """

        self._group_id = group_id

    @property
    def is_active(self):
        """
        Gets the is_active of this PrivateAuthorsSearch.
        Return only active authors if True

        :return: The is_active of this PrivateAuthorsSearch.
        :rtype: bool
        """
        return self._is_active

    @is_active.setter
    def is_active(self, is_active):
        """
        Sets the is_active of this PrivateAuthorsSearch.
        Return only active authors if True

        :param is_active: The is_active of this PrivateAuthorsSearch.
        :type: bool
        """

        self._is_active = is_active

    @property
    def is_public(self):
        """
        Gets the is_public of this PrivateAuthorsSearch.
        Return only authors that have published items if True

        :return: The is_public of this PrivateAuthorsSearch.
        :rtype: bool
        """
        return self._is_public

    @is_public.setter
    def is_public(self, is_public):
        """
        Sets the is_public of this PrivateAuthorsSearch.
        Return only authors that have published items if True

        :param is_public: The is_public of this PrivateAuthorsSearch.
        :type: bool
        """

        self._is_public = is_public

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PrivateAuthorsSearch):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
