# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ProjectNotePrivate(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'user_id': 'int',
        'abstract': 'str',
        'user_name': 'str',
        'created_date': 'str',
        'modified_date': 'str'
    }

    attribute_map = {
        'id': 'id',
        'user_id': 'user_id',
        'abstract': 'abstract',
        'user_name': 'user_name',
        'created_date': 'created_date',
        'modified_date': 'modified_date'
    }

    def __init__(self, id=None, user_id=None, abstract=None, user_name=None, created_date=None, modified_date=None):
        """
        ProjectNotePrivate - a model defined in Swagger
        """

        self._id = None
        self._user_id = None
        self._abstract = None
        self._user_name = None
        self._created_date = None
        self._modified_date = None

        self.id = id
        self.user_id = user_id
        self.abstract = abstract
        self.user_name = user_name
        self.created_date = created_date
        self.modified_date = modified_date

    @property
    def id(self):
        """
        Gets the id of this ProjectNotePrivate.
        Project note id

        :return: The id of this ProjectNotePrivate.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this ProjectNotePrivate.
        Project note id

        :param id: The id of this ProjectNotePrivate.
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def user_id(self):
        """
        Gets the user_id of this ProjectNotePrivate.
        User who wrote the note

        :return: The user_id of this ProjectNotePrivate.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """
        Sets the user_id of this ProjectNotePrivate.
        User who wrote the note

        :param user_id: The user_id of this ProjectNotePrivate.
        :type: int
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")

        self._user_id = user_id

    @property
    def abstract(self):
        """
        Gets the abstract of this ProjectNotePrivate.
        Note Abstract - short/truncated content

        :return: The abstract of this ProjectNotePrivate.
        :rtype: str
        """
        return self._abstract

    @abstract.setter
    def abstract(self, abstract):
        """
        Sets the abstract of this ProjectNotePrivate.
        Note Abstract - short/truncated content

        :param abstract: The abstract of this ProjectNotePrivate.
        :type: str
        """
        if abstract is None:
            raise ValueError("Invalid value for `abstract`, must not be `None`")

        self._abstract = abstract

    @property
    def user_name(self):
        """
        Gets the user_name of this ProjectNotePrivate.
        Username of the one who wrote the note

        :return: The user_name of this ProjectNotePrivate.
        :rtype: str
        """
        return self._user_name

    @user_name.setter
    def user_name(self, user_name):
        """
        Sets the user_name of this ProjectNotePrivate.
        Username of the one who wrote the note

        :param user_name: The user_name of this ProjectNotePrivate.
        :type: str
        """
        if user_name is None:
            raise ValueError("Invalid value for `user_name`, must not be `None`")

        self._user_name = user_name

    @property
    def created_date(self):
        """
        Gets the created_date of this ProjectNotePrivate.
        Date when note was created

        :return: The created_date of this ProjectNotePrivate.
        :rtype: str
        """
        return self._created_date

    @created_date.setter
    def created_date(self, created_date):
        """
        Sets the created_date of this ProjectNotePrivate.
        Date when note was created

        :param created_date: The created_date of this ProjectNotePrivate.
        :type: str
        """
        if created_date is None:
            raise ValueError("Invalid value for `created_date`, must not be `None`")

        self._created_date = created_date

    @property
    def modified_date(self):
        """
        Gets the modified_date of this ProjectNotePrivate.
        Date when note was last modified

        :return: The modified_date of this ProjectNotePrivate.
        :rtype: str
        """
        return self._modified_date

    @modified_date.setter
    def modified_date(self, modified_date):
        """
        Sets the modified_date of this ProjectNotePrivate.
        Date when note was last modified

        :param modified_date: The modified_date of this ProjectNotePrivate.
        :type: str
        """
        if modified_date is None:
            raise ValueError("Invalid value for `modified_date`, must not be `None`")

        self._modified_date = modified_date

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ProjectNotePrivate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
