# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ProjectCollaboratorInvite(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'role_name': 'str',
        'user_id': 'int',
        'email': 'str',
        'comment': 'str'
    }

    attribute_map = {
        'role_name': 'role_name',
        'user_id': 'user_id',
        'email': 'email',
        'comment': 'comment'
    }

    def __init__(self, role_name=None, user_id=None, email=None, comment=None):
        """
        ProjectCollaboratorInvite - a model defined in Swagger
        """

        self._role_name = None
        self._user_id = None
        self._email = None
        self._comment = None

        self.role_name = role_name
        if user_id is not None:
          self.user_id = user_id
        if email is not None:
          self.email = email
        if comment is not None:
          self.comment = comment

    @property
    def role_name(self):
        """
        Gets the role_name of this ProjectCollaboratorInvite.
        Role of the the collaborator inside the project

        :return: The role_name of this ProjectCollaboratorInvite.
        :rtype: str
        """
        return self._role_name

    @role_name.setter
    def role_name(self, role_name):
        """
        Sets the role_name of this ProjectCollaboratorInvite.
        Role of the the collaborator inside the project

        :param role_name: The role_name of this ProjectCollaboratorInvite.
        :type: str
        """
        if role_name is None:
            raise ValueError("Invalid value for `role_name`, must not be `None`")
        allowed_values = ["viewer", "collaborator"]
        if role_name not in allowed_values:
            raise ValueError(
                "Invalid value for `role_name` ({0}), must be one of {1}"
                .format(role_name, allowed_values)
            )

        self._role_name = role_name

    @property
    def user_id(self):
        """
        Gets the user_id of this ProjectCollaboratorInvite.
        User id of the collaborator

        :return: The user_id of this ProjectCollaboratorInvite.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """
        Sets the user_id of this ProjectCollaboratorInvite.
        User id of the collaborator

        :param user_id: The user_id of this ProjectCollaboratorInvite.
        :type: int
        """

        self._user_id = user_id

    @property
    def email(self):
        """
        Gets the email of this ProjectCollaboratorInvite.
        Collaborator email

        :return: The email of this ProjectCollaboratorInvite.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """
        Sets the email of this ProjectCollaboratorInvite.
        Collaborator email

        :param email: The email of this ProjectCollaboratorInvite.
        :type: str
        """

        self._email = email

    @property
    def comment(self):
        """
        Gets the comment of this ProjectCollaboratorInvite.
        Text sent when inviting the user to the project

        :return: The comment of this ProjectCollaboratorInvite.
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """
        Sets the comment of this ProjectCollaboratorInvite.
        Text sent when inviting the user to the project

        :param comment: The comment of this ProjectCollaboratorInvite.
        :type: str
        """

        self._comment = comment

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ProjectCollaboratorInvite):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
