# coding: utf-8

"""
    Figshare API

    Figshare apiv2. Using Swagger 2.0

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Timeline(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'first_online': 'str',
        'publisher_publication': 'str',
        'publisher_acceptance': 'str'
    }

    attribute_map = {
        'first_online': 'firstOnline',
        'publisher_publication': 'publisherPublication',
        'publisher_acceptance': 'publisherAcceptance'
    }

    def __init__(self, first_online=None, publisher_publication=None, publisher_acceptance=None):
        """
        Timeline - a model defined in Swagger
        """

        self._first_online = None
        self._publisher_publication = None
        self._publisher_acceptance = None

        if first_online is not None:
          self.first_online = first_online
        if publisher_publication is not None:
          self.publisher_publication = publisher_publication
        if publisher_acceptance is not None:
          self.publisher_acceptance = publisher_acceptance

    @property
    def first_online(self):
        """
        Gets the first_online of this Timeline.
        Online posted date

        :return: The first_online of this Timeline.
        :rtype: str
        """
        return self._first_online

    @first_online.setter
    def first_online(self, first_online):
        """
        Sets the first_online of this Timeline.
        Online posted date

        :param first_online: The first_online of this Timeline.
        :type: str
        """

        self._first_online = first_online

    @property
    def publisher_publication(self):
        """
        Gets the publisher_publication of this Timeline.
        Publish date

        :return: The publisher_publication of this Timeline.
        :rtype: str
        """
        return self._publisher_publication

    @publisher_publication.setter
    def publisher_publication(self, publisher_publication):
        """
        Sets the publisher_publication of this Timeline.
        Publish date

        :param publisher_publication: The publisher_publication of this Timeline.
        :type: str
        """

        self._publisher_publication = publisher_publication

    @property
    def publisher_acceptance(self):
        """
        Gets the publisher_acceptance of this Timeline.
        Date when the item was accepted for publication

        :return: The publisher_acceptance of this Timeline.
        :rtype: str
        """
        return self._publisher_acceptance

    @publisher_acceptance.setter
    def publisher_acceptance(self, publisher_acceptance):
        """
        Sets the publisher_acceptance of this Timeline.
        Date when the item was accepted for publication

        :param publisher_acceptance: The publisher_acceptance of this Timeline.
        :type: str
        """

        self._publisher_acceptance = publisher_acceptance

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Timeline):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
